### ISSUE TITLE
native build failed for smb+quartz

### ISSUE THREAD

**Issue by robotrader** [apache/camel-quarkus#8158]
### Bug description

https://camel.zulipchat.com/#narrow/channel/257302-camel-quarkus/topic/native.20build.20failed.20for.20smb.2Bquartz/with/568173900

When project has dependencies for camel-quarkus-quartz&camel-quarkus-smb native build fails with stacktrace

```
Error: Class initialization of net.engio.mbassy.dispatch.el.StandardELResolutionContext failed. This error is reported at image build time because class net.engio.mbassy.dispatch.el.StandardELResolutionContext is registered for linking at image build time by command line and command line.
....................................
Caused by: java.lang.NoClassDefFoundError: javax/el/FunctionMapper
Caused by: java.lang.ClassNotFoundException: javax.el.FunctionMapper
```

**How to reproduce**
Clone https://github.com/apache/camel-quarkus-examples
Add dependencies to camel-quarkus-examples/timer-log/pom.xml
```
<dependency>
    <groupId>org.apache.camel.quarkus</groupId>
    <artifactId>camel-quarkus-quartz</artifactId>
</dependency>
<dependency>
    <groupId>org.apache.camel.quarkus</groupId>
    <artifactId>camel-quarkus-smb</artifactId>
</dependency>
```
Go to folder camel-quarkus-examples/timer-log and run command (build using Docker)
```
mvn -DskipTests=true package -Dnative -Dquarkus.native.container-build=true -Dquarkus.container-image.build=true -Dquarkus.container-image.push=false

```
I have checked all dependencies in project and didn't find mbassador dependency.
It seems, that mbassador used at build time only

And, if remove smb OR quartz from dependencies, each of them works fine separately.

**Comment by jamesnetherton** [comment]
This is odd because we bytecode transform javax.el imports to jakarta.el:

https://github.com/apache/camel-quarkus/blob/main/extensions/smb/deployment/src/main/java/org/apache/camel/quarkus/component/smb/deployment/JakartaEnablement.java

**Comment by jamesnetherton** [comment]
The cause seems to be `org.glassfish.expressly:expressly` getting added to the classpath from quarkus-scheduler.

https://github.com/quarkusio/quarkus/blob/a65afc6cc2558eaf5e9de6a271e2385ab0c1454f/extensions/scheduler/runtime/pom.xml#L36-L39

We'll probably need to forcefully disable EL support in `net.engio:mbassador` in native mode. From what I can see `smbj` does not make use of that feature. So it should be safe.
