### ISSUE TITLE
[quarkus-main] Nitrite integration test native build fails

### ISSUE THREAD

**Issue by jamesnetherton** [apache/camel-quarkus#8246]
### Bug description

Native compilation fails with `648 fatal errors detected`.

The logs are full of `NoClassDefFoundError` exceptions for types that are unrelated to Nitrite. I'm not sure why. It could be related to the compiler finding paths to types via the component / endpoint DSLs or the Camel catalog.

Another case possibly caused by https://github.com/quarkusio/quarkus/pull/52313.

Since camel-nitrite is deprecated, there's not much value in investigating too deeply IMO.

I will disable the Nitrite native test profile.

**Comment by apupier** [comment]
Nitrite component removed for Camel 4.19 https://issues.apache.org/jira/browse/CAMEL-23095

**Comment by apupier** [comment]
I will remove it from camel-main branch of Camel Quarkus

**Comment by jamesnetherton** [comment]
Nitrite removed in https://github.com/apache/camel-quarkus/pull/8518.
