### ISSUE TITLE
LevelDB extension does not compile with Camel 3.7.0-SNAPSHOT

### ISSUE THREAD

**Issue by jamesnetherton** [apache/camel-quarkus#1948]
I guess this happens because the Camel component has been reworked.

@JiriOndrusek can you take a look into this on the camel-master branch?

```
[ERROR] camel-quarkus/extensions/leveldb/runtime/src/main/java/org/apache/camel/quarkus/component/leveldb/ObjectCodecSubstitute.java:[30,36] package org.fusesource.hawtbuf.codec does not exist
[ERROR] camel-quarkus/extensions/leveldb/runtime/src/main/java/org/apache/camel/quarkus/component/leveldb/ObjectCodecSubstitute.java:[38,22] cannot find symbol
```

**Comment by JiriOndrusek** [comment]
@jamesnetherton yes, my plan was to fix cq extension today. Please assign to me
