### PR TITLE
Upgrade Quarkus to 2.14.0.CR1

### PR DESCRIPTION
**Pull request by jamesnetherton**

### CODE REVIEW

**Review by oscerd — APPROVED** [review]

**Comment by jamesnetherton** [comment]
Seems there are a few native breakages:

```
2022-10-26T16:38:15.5728805Z Exception in thread "main" java.lang.ExceptionInInitializerError
2022-10-26T16:38:15.5729365Z 	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
2022-10-26T16:38:15.5729964Z 	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
2022-10-26T16:38:15.5730612Z 	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
2022-10-26T16:38:15.5731170Z 	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
2022-10-26T16:38:15.5734533Z 	at java.base/java.lang.Class.newInstance(Class.java:584)
2022-10-26T16:38:15.5737492Z 	at io.quarkus.runtime.Quarkus.run(Quarkus.java:68)
2022-10-26T16:38:15.5740505Z 	at io.quarkus.runtime.Quarkus.run(Quarkus.java:42)
2022-10-26T16:38:15.5744811Z 	at io.quarkus.runtime.Quarkus.run(Quarkus.java:122)
2022-10-26T16:38:15.5745159Z 	at io.quarkus.runner.GeneratedMain.main(Unknown Source)
2022-10-26T16:38:15.5750399Z Caused by: java.lang.RuntimeException: Failed to start quarkus
2022-10-26T16:38:15.5750856Z 	at io.quarkus.runner.ApplicationImpl.<clinit>(Unknown Source)
2022-10-26T16:38:15.5755070Z 	... 9 more
2022-10-26T16:38:15.5758796Z Caused by: java.lang.NoClassDefFoundError: org/graalvm/nativeimage/ImageInfo
2022-10-26T16:38:15.5761893Z 	at io.quarkus.runtime.logging.LoggingSetupRecorder.initializeLoggingForImageBuild(LoggingSetupRecorder.java:494)
2022-10-26T16:38:15.5763145Z 	at io.quarkus.deployment.steps.LoggingResourceProcessor$setupLoggingStaticInit2062061316.deploy_0(Unknown Source)
2022-10-26T16:38:15.5765120Z 	at io.quarkus.deployment.steps.LoggingResourceProcessor$setupLoggingStaticInit2062061316.deploy(Unknown Source)
2022-10-26T16:38:15.5765786Z 	... 10 more
2022-10-26T16:38:15.5768408Z Caused by: java.lang.ClassNotFoundException: org.graalvm.nativeimage.ImageInfo
2022-10-26T16:38:15.5769172Z 	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
2022-10-26T16:38:15.5771621Z 	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
2022-10-26T16:38:15.5772044Z 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
2022-10-26T16:38:15.5776123Z 	... 13 more
```

**Comment by jamesnetherton** [comment]
Native failures are probably related to this change:

https://github.com/quarkusio/quarkus/commit/2ae0c0ee442d692706df1104c412276fe5573e8b

I'll disable the native tests in the affected areas for now and open an issue.

**Review by aldettinger — APPROVED** [review]
Ok, I see kubernetes itests restored and quartz depended upon some work in quarkus 2.14.x.
Hope the native issues won't have too much impact :crossed_fingers:
