### ISSUE TITLE
Build/test fail on camel-quarkus app for quarkus-minio (client) version since 3.9.0

### ISSUE THREAD

**Issue by janwesterkamp** [apache/camel-quarkus#9002]
### Bug description

NOTE: This is a clone of the [original issue 545]https://github.com/quarkiverse/quarkus-minio/issues/545
 filed in quarkiverse/quarkus-minio to track interference.

When updating (camel-)quarkus app quarkus-minio version from 3.8.6 to 3.9.0+ (tested with 3.9.0 and 3.9.1), testing fails with the following exception:

```
java.lang.RuntimeException: java.lang.RuntimeException: Failed to start quarkus
	at io.quarkus.test.junit.QuarkusTestExtension.throwBootFailureException(QuarkusTestExtension.java:670)
	at io.quarkus.test.junit.QuarkusTestExtension.interceptTestClassConstructor(QuarkusTestExtension.java:765)
	at java.base/java.util.Optional.orElseGet(Optional.java:364)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
Caused by: java.lang.RuntimeException: Failed to start quarkus
	at io.quarkus.runner.ApplicationImpl.doStart(Unknown Source)
	at io.quarkus.runtime.Application.start(Application.java:112)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at io.quarkus.runner.bootstrap.StartupActionImpl.run(StartupActionImpl.java:399)
	at io.quarkus.test.junit.QuarkusTestExtension.doJavaStart(QuarkusTestExtension.java:232)
	at io.quarkus.test.junit.QuarkusTestExtension.ensureStarted(QuarkusTestExtension.java:644)
	at io.quarkus.test.junit.QuarkusTestExtension.beforeAll(QuarkusTestExtension.java:689)
	... 1 more
Caused by: java.lang.NoSuchMethodError: 'okhttp3.HttpUrl io.minio.Utils.getBaseUrl(java.lang.String)'
	at io.quarkiverse.minio.client.MinioClients.lambda$createMinioClient$2(MinioClients.java:87)
	at java.base/java.util.Optional.ifPresentOrElse(Optional.java:198)
	at io.quarkiverse.minio.client.MinioClients.createMinioClient(MinioClients.java:84)
	at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1708)
	at io.quarkiverse.minio.client.MinioClients.getMinioClient(MinioClients.java:72)
	at io.quarkiverse.minio.client.MinioClients.fromName(MinioClients.java:52)
	at io.quarkiverse.minio.client.MinioRecorder.lambda$minioClientSupplier$0(MinioRecorder.java:13)
	at io.quarkus.arc.runtime.ArcRecorder$4.apply(ArcRecorder.java:138)
	at io.quarkus.arc.runtime.ArcRecorder$4.apply(ArcRecorder.java:135)
	at io.minio.MinioClient_zaOO10OoeJ7Aafa5tSe8y7rN0qQ_Synthetic_Bean.createSynthetic(Unknown Source)
	at io.minio.MinioClient_zaOO10OoeJ7Aafa5tSe8y7rN0qQ_Synthetic_Bean.create(Unknown Source)
	at io.minio.MinioClient_zaOO10OoeJ7Aafa5tSe8y7rN0qQ_Synthetic_Bean.create(Unknown Source)
	at io.quarkus.arc.impl.AbstractSharedContext.createInstanceHandle(AbstractSharedContext.java:119)
	at io.quarkus.arc.impl.AbstractSharedContext$1.get(AbstractSharedContext.java:38)
	at io.quarkus.arc.impl.AbstractSharedContext$1.get(AbstractSharedContext.java:35)
	at io.quarkus.arc.impl.LazyValue.get(LazyValue.java:32)
	at io.quarkus.arc.impl.ComputingCache.computeIfAbsent(ComputingCache.java:69)
	at io.quarkus.arc.impl.ComputingCacheContextInstances.computeIfAbsent(ComputingCacheContextInstances.java:19)
	at io.quarkus.arc.impl.AbstractSharedContext.get(AbstractSharedContext.java:35)
	at io.minio.MinioClient_zaOO10OoeJ7Aafa5tSe8y7rN0qQ_Synthetic_Bean.get(Unknown Source)
	at io.minio.MinioClient_zaOO10OoeJ7Aafa5tSe8y7rN0qQ_Synthetic_Bean.get(Unknown Source)
	at io.quarkus.arc.impl.Instances$3.get(Instances.java:130)
	at io.quarkus.arc.impl.LazyValue.get(LazyValue.java:32)
	at io.quarkus.arc.impl.LazyInstanceHandle.instanceInternal(LazyInstanceHandle.java:34)
	at io.quarkus.arc.impl.AbstractInstanceHandle.get(AbstractInstanceHandle.java:42)
	at org.apache.camel.quarkus.core.RuntimeBeanRepository.findSingleByType(RuntimeBeanRepository.java:117)
	at org.apache.camel.support.DefaultRegistry.findSingleByType(DefaultRegistry.java:434)
	at org.apache.camel.support.LifecycleStrategySupport.doAutoWire(LifecycleStrategySupport.java:259)
	at org.apache.camel.main.MainAutowiredLifecycleStrategy.autowire(MainAutowiredLifecycleStrategy.java:136)
	at org.apache.camel.main.MainAutowiredLifecycleStrategy.autowireComponent(MainAutowiredLifecycleStrategy.java:119)
	at org.apache.camel.main.MainAutowiredLifecycleStrategy.onComponentAdd(MainAutowiredLifecycleStrategy.java:75)
	at org.apache.camel.impl.engine.AbstractCamelContext.postInitComponent(AbstractCamelContext.java:517)
	at org.apache.camel.impl.engine.AbstractCamelContext.initComponent(AbstractCamelContext.java:611)
	at org.apache.camel.impl.engine.AbstractCamelContext.lambda$getComponent$0(AbstractCamelContext.java:550)
	at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1708)
	at org.apache.camel.impl.engine.AbstractCamelContext.getComponent(AbstractCamelContext.java:548)
	at org.apache.camel.impl.engine.AbstractCamelContext.getComponent(AbstractCamelContext.java:523)
	at org.apache.camel.impl.engine.AbstractCamelContext.doGetEndpoint(AbstractCamelContext.java:849)
	at org.apache.camel.impl.engine.AbstractCamelContext.getEndpoint(AbstractCamelContext.java:778)
	at org.apache.camel.support.CamelContextHelper.resolveEndpoint(CamelContextHelper.java:156)
	at org.apache.camel.reifier.SendReifier.resolveEndpoint(SendReifier.java:59)
	at org.apache.camel.reifier.SendReifier.createProcessor(SendReifier.java:48)
	at org.apache.camel.reifier.ProcessorReifier.lambda$createProcessor$0(ProcessorReifier.java:838)
	at org.apache.camel.impl.engine.DefaultCamelContextExtension.lambda$createProcessor$0(DefaultCamelContextExtension.java:471)
	at org.apache.camel.util.concurrent.ContextValueFactory.where(ContextValueFactory.java:65)
	at org.apache.camel.util.concurrent.ContextValue.where(ContextValue.java:174)
	at org.apache.camel.impl.engine.DefaultCamelContextExtension.createProcessor(DefaultCamelContextExtension.java:469)
	at org.apache.camel.reifier.ProcessorReifier.createProcessor(ProcessorReifier.java:829)
	at org.apache.camel.reifier.ProcessorReifier.createOutputsProcessor(ProcessorReifier.java:780)
	at org.apache.camel.reifier.ProcessorReifier.createOutputsProcessor(ProcessorReifier.java:769)
	at org.apache.camel.reifier.TryReifier.createProcessor(TryReifier.java:38)
	at org.apache.camel.reifier.ProcessorReifier.lambda$makeProcessor$0(ProcessorReifier.java:865)
	at org.apache.camel.impl.engine.DefaultCamelContextExtension.lambda$createProcessor$0(DefaultCamelContextExtension.java:471)
	at org.apache.camel.util.concurrent.ContextValueFactory.where(ContextValueFactory.java:65)
	at org.apache.camel.util.concurrent.ContextValue.where(ContextValue.java:174)
	at org.apache.camel.impl.engine.DefaultCamelContextExtension.createProcessor(DefaultCamelContextExtension.java:469)
	at org.apache.camel.reifier.ProcessorReifier.makeProcessor(ProcessorReifier.java:851)
	at org.apache.camel.reifier.ProcessorReifier.addRoutes(ProcessorReifier.java:624)
	at org.apache.camel.reifier.RouteReifier.doCreateRoute(RouteReifier.java:240)
	at org.apache.camel.reifier.RouteReifier.createRoute(RouteReifier.java:89)
	at org.apache.camel.impl.DefaultModelReifierFactory.createRoute(DefaultModelReifierFactory.java:49)
	at org.apache.camel.impl.DefaultCamelContext.lambda$doStartRouteDefinitions$2(DefaultCamelContext.java:780)
	at org.apache.camel.util.concurrent.ContextValueFactory.lambda$where$0(ContextValueFactory.java:82)
	at org.apache.camel.util.concurrent.ContextValueFactory.where(ContextValueFactory.java:65)
	at org.apache.camel.util.concurrent.ContextValueFactory.where(ContextValueFactory.java:81)
	at org.apache.camel.util.concurrent.ContextValue.where(ContextValue.java:186)
	at org.apache.camel.impl.engine.DefaultCamelContextExtension.createRoute(DefaultCamelContextExtension.java:436)
	at org.apache.camel.impl.DefaultCamelContext.doStartRouteDefinitions(DefaultCamelContext.java:778)
	at org.apache.camel.impl.DefaultCamelContext.lambda$startRouteDefinitions$0(DefaultCamelContext.java:641)
	at org.apache.camel.impl.engine.AbstractCamelContext.lambda$startingRoutes$0(AbstractCamelContext.java:1165)
	at org.apache.camel.util.concurrent.ContextValueFactory.where(ContextValueFactory.java:65)
	at org.apache.camel.util.concurrent.ContextValue.where(ContextValue.java:174)
	at org.apache.camel.impl.engine.AbstractCamelContext.startingRoutes(AbstractCamelContext.java:1163)
	at org.apache.camel.impl.DefaultCamelContext.startRouteDefinitions(DefaultCamelContext.java:640)
	at org.apache.camel.impl.DefaultCamelContext.startRouteDefinitions(DefaultCamelContext.java:622)
	at org.apache.camel.impl.engine.AbstractCamelContext.doInit(AbstractCamelContext.java:2717)
	at org.apache.camel.quarkus.core.FastCamelContext.doInit(FastCamelContext.java:195)
	at org.apache.camel.support.service.BaseService.init(BaseService.java:94)
	at org.apache.camel.impl.engine.AbstractCamelContext.init(AbstractCamelContext.java:2328)
	at org.apache.camel.support.service.BaseService.start(BaseService.java:124)
	at org.apache.camel.impl.engine.AbstractCamelContext.start(AbstractCamelContext.java:2347)
	at org.apache.camel.impl.DefaultCamelContext.start(DefaultCamelContext.java:214)
	at org.apache.camel.quarkus.main.CamelMain.doStart(CamelMain.java:71)
	at org.apache.camel.support.service.BaseService.start(BaseService.java:132)
	at org.apache.camel.quarkus.main.CamelMain.startEngine(CamelMain.java:128)
	at org.apache.camel.quarkus.main.CamelMainRuntime.start(CamelMainRuntime.java:49)
	at org.apache.camel.quarkus.core.CamelBootstrapRecorder.start(CamelBootstrapRecorder.java:51)
	at io.quarkus.runner.recorded.CamelBootstrapProcessor$boot173480958.deploy_0(Unknown Source)
	at io.quarkus.runner.recorded.CamelBootstrapProcessor$boot173480958.deploy(Unknown Source)
	... 8 more
```

I tested the behaviour with Quarkus version 3.37.4, 3.38.0, 3.38.1 and 3.39.0.CR1 of the app, where 3.38.x is referencing Camel Quarkus 3.38.0 and Camel 4.21.0.

Output of uname -a or ver

Darwin MacBookPro.fritz.box 24.6.0 Darwin Kernel Version 24.6.0: Tue Jul 21 20:50:07 PDT 2026; root:xnu-11417.140.69.711.44~1/RELEASE_X86_64 x86_64

Output of java -version

graalvm-community-openjdk-25.0.1+8.1, but build to release 21 by maven

Quarkus version or git rev

3.38.0.CR1

Build tool (ie. output of mvnw --version or gradlew --version)

Eclipse IDE embedded Maven 3.9.16

Workaround:

Stick to quarkus-minio extension version 3.8.6.

Additional information:

Camel 4.22.0 is updating to minio-java (client) 9.x too, this might fix it, but there is no matching camel-quarkus version available yet to verify this.

**Comment by jamesnetherton** [comment]
Yes, it's expected that it'll break if you bump to Mino 9.x with Camel Quarkus <= 3.38.x. 

It'll be fixed in Camel Quarkus 3.39.0 where we'll have Camel 4.22.0 and quarkus-minio 3.9.1.

**Comment by jamesnetherton** [comment]
I'll close this as the work needed to support Minio 9.x is completed for Camel Quarkus 3.39.0.
