### ISSUE TITLE
XPathAPI does not work in native mode

### ISSUE THREAD

**Issue by turing85** [apache/camel-quarkus#4710]
`XPathAPI` is part of xalan, which is a transitive dependency of `camel-quarkus-xslt`:
```bash
$ mvn dependency:tree
...
[INFO] +- org.apache.camel.quarkus:camel-quarkus-xslt:jar:2.13.2:compile
[INFO] |  +- io.quarkus:quarkus-jaxp:jar:2.13.7.Final:compile
[INFO] |  +- org.apache.camel.quarkus:camel-quarkus-support-xalan:jar:2.13.2:compile
[INFO] |  |  \- xalan:xalan:jar:2.7.2:compile
...
```

Depending on the exact quarkus-version used, the usage of `XPathAPI` in a native application leads to different, erroneous behaviour.

<details>
<summary><h2>Behaviour in quarkus version 2.13.X.Final</h2></summary>
The application compiles fine, but fails at runtime with:

```
2023-03-22 02:15:21,660 ERROR [org.apa.cam.pro.err.DefaultErrorHandler] (executor-thread-0) Failed delivery for (MessageId: 26CEA3B261100AA-0000000000000000 on ExchangeId: 26CEA3B261100AA-0000000000000000). Exhausted after delivery attempt: 1 caught: java.util.MissingResourceException: Could not load any resource bundles.org.apache.xml.res.XMLErrorResources

Message History (source location and message history is disabled)
---------------------------------------------------------------------------------------------------------------------------------------
Source                                   ID                             Processor                                          Elapsed (ms)
                                         route1/route1                  from[platform-http:///hello?httpMethodRestrict=POS            1
	...
                                         route1/process1                Processor@0x2d479a84                                          0

Stacktrace
---------------------------------------------------------------------------------------------------------------------------------------: java.util.MissingResourceException: Could not load any resource bundles.org.apache.xml.res.XMLErrorResources
	at org.apache.xml.res.XMLMessages.loadResourceBundle(XMLMessages.java:189)
	at org.apache.xml.res.XMLMessages.createXMLMessage(XMLMessages.java:84)
	at org.apache.xml.utils.ObjectPool.getInstance(ObjectPool.java:142)
	at org.apache.xml.utils.StringBufferPool.get(StringBufferPool.java:44)
	at org.apache.xml.dtm.ref.dom2dtm.DOM2DTM.getStringValue(DOM2DTM.java:822)
	at org.apache.xpath.objects.XNodeSet.getStringFromNode(XNodeSet.java:217)
	at org.apache.xpath.objects.XNodeSet.str(XNodeSet.java:280)
	at org.apache.xpath.objects.XObject.toString(XObject.java:312)
	at de.turing85.MyProcessor.process(MyProcessor.java:14)
	at de.turing85.MyProcessor_ClientProxy.process(Unknown Source)
	at org.apache.camel.support.processor.DelegateSyncProcessor.process(DelegateSyncProcessor.java:65)
	at org.apache.camel.processor.errorhandler.RedeliveryErrorHandler$SimpleTask.run(RedeliveryErrorHandler.java:477)
	at org.apache.camel.impl.engine.DefaultReactiveExecutor$Worker.schedule(DefaultReactiveExecutor.java:189)
	at org.apache.camel.impl.engine.DefaultReactiveExecutor.scheduleMain(DefaultReactiveExecutor.java:61)
	at org.apache.camel.processor.Pipeline.process(Pipeline.java:182)
	at org.apache.camel.impl.engine.CamelInternalProcessor.process(CamelInternalProcessor.java:399)
	at org.apache.camel.component.platform.http.vertx.VertxPlatformHttpConsumer.lambda$handleRequest$2(VertxPlatformHttpConsumer.java:201)
	at io.vertx.core.impl.ContextBase.lambda$null$0(ContextBase.java:137)
	at io.vertx.core.impl.ContextInternal.dispatch(ContextInternal.java:264)
	at io.vertx.core.impl.ContextBase.lambda$executeBlocking$1(ContextBase.java:135)
	at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:576)
	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1478)
	at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
	at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base@17.0.5/java.lang.Thread.run(Thread.java:833)
	at org.graalvm.nativeimage.builder/com.oracle.svm.core.thread.PlatformThreads.threadStartRoutine(PlatformThreads.java:775)
	at org.graalvm.nativeimage.builder/com.oracle.svm.core.posix.thread.PosixPlatformThreads.pthreadStartRoutine(PosixPlatformThreads.java:203)
```
### Reproducer
* Checkout the project
    ```bash
    git clone git@github.com:turing85/quarkus-camel-xslt.git
    cd quarkus-camel-xslt
    ```

* Build the project, execute all tests
    ```bash
    ./mvn clean verify
    ```

* Notice that all tests succeed

* Repeat, but with native compilation activated
    ```bash
    ./mvnw --define native clean verify
    ```

* Notice that the quarkus tests succeed
    ```
    ...
    [INFO] --- maven-surefire-plugin:3.0.0-M7:test (default-test) @ quarkus-camel-xslt ---
    ...
    [INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 5.348 s - in de.turing85.GreetingResourceTest
    ...
    ```

* Notice that the integration tests fail with above error
</details>
<details>
<summary><h2>Behaviour in 2.16.X.Final</h2></summary>
Native compilation fails with:

```
...
[INFO] [io.quarkus.deployment.pkg.steps.NativeImageBuildRunner] /opt/java/mandrel/22.3.0.1-java17/bin/native-image -J-Dsun.nio.ch.maxUpdateArraySize=100 -J-Dvertx.logger-delegate-factory-class-name=io.quarkus.vertx.core.runtime.VertxLogDelegateFactory -J-Dvertx.disableDnsResolver=true -J-Dio.netty.noUnsafe=true -J-Dio.netty.leakDetection.level=DISABLED -J-Dio.netty.allocator.maxOrder=3 -J-Djava.util.logging.manager=org.jboss.logmanager.LogManager -J-Dlogging.initial-configurator.min-level=500 -J-Duser.language=en -J-Duser.country=US -J-Dfile.encoding=UTF-8 --features=io.quarkus.runner.Feature,io.quarkus.runtime.graal.ResourcesFeature,io.quarkus.runtime.graal.DisableLoggingFeature -J--add-exports=java.security.jgss/sun.security.krb5=ALL-UNNAMED -J--add-opens=java.base/java.text=ALL-UNNAMED -J--add-opens=java.base/java.io=ALL-UNNAMED -J--add-opens=java.base/java.lang.invoke=ALL-UNNAMED -J--add-opens=java.base/java.util=ALL-UNNAMED -H:+CollectImageBuildStatistics -H:ImageBuildStatisticsFile=quarkus-camel-xslt-1.0.0-SNAPSHOT-runner-timing-stats.json -H:BuildOutputJSONFile=quarkus-camel-xslt-1.0.0-SNAPSHOT-runner-build-output-stats.json -H:+AllowFoldMethods -J-Djava.awt.headless=true --no-fallback --link-at-build-time -H:+ReportExceptionStackTraces -H:-AddAllCharsets --enable-url-protocols=http -H:NativeLinkerOption=-no-pie -H:-UseServiceLoaderFeature -H:+StackTrace -J--add-exports=org.graalvm.sdk/org.graalvm.nativeimage.impl=ALL-UNNAMED -J--add-exports=org.graalvm.nativeimage.builder/com.oracle.svm.core.jdk=ALL-UNNAMED --exclude-config io\.netty\.netty-codec /META-INF/native-image/io\.netty/netty-codec/generated/handlers/reflect-config\.json --exclude-config io\.netty\.netty-handler /META-INF/native-image/io\.netty/netty-handler/generated/handlers/reflect-config\.json quarkus-camel-xslt-1.0.0-SNAPSHOT-runner -jar quarkus-camel-xslt-1.0.0-SNAPSHOT-runner.jar
========================================================================================================================
GraalVM Native Image: Generating 'quarkus-camel-xslt-1.0.0-SNAPSHOT-runner' (executable)...
========================================================================================================================
Warning: Feature class org.apache.camel.quarkus.support.xalan.deployment.XalanNativeImageProcessorAutoFeature is annotated with the deprecated annotation @AutomaticFeature. Support for this annotation will be removed in a future version of GraalVM. Applications should register a feature using the option --features=org.apache.camel.quarkus.support.xalan.deployment.XalanNativeImageProcessorAutoFeature
[1/7] Initializing...                                                                                    (6.6s @ 0.28GB)
 Version info: 'GraalVM 22.3.0.1-Final Java 17 Mandrel Distribution'
 Java version info: '17.0.5+8'
 C compiler: gcc (linux, x86_64, 11.3.0)
 Garbage collector: Serial GC
 4 user-specific feature(s)
 - io.quarkus.runner.Feature: Auto-generated class by Quarkus from the existing extensions
 - io.quarkus.runtime.graal.DisableLoggingFeature: Disables INFO logging during the analysis phase for the [org.jboss.threads] categories
 - io.quarkus.runtime.graal.ResourcesFeature: Register each line in META-INF/quarkus-native-resources.txt as a resource on Substrate VM
 - org.apache.camel.quarkus.support.xalan.deployment.XalanNativeImageProcessorAutoFeature
java.lang.ClassNotFoundException: org.apache.hc.client5.http.impl.auth.NTLMEngineImpl
	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:445)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:587)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:467)
	at io.quarkus.runner.Feature.runtimeInitializedClasses(Unknown Source)
	at io.quarkus.runner.Feature.beforeAnalysis(Unknown Source)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGenerator.lambda$runPointsToAnalysis$9(NativeImageGenerator.java:736)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.FeatureHandler.forEachFeature(FeatureHandler.java:85)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGenerator.runPointsToAnalysis(NativeImageGenerator.java:736)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:578)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGenerator.run(NativeImageGenerator.java:535)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGeneratorRunner.buildImage(NativeImageGeneratorRunner.java:403)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGeneratorRunner.build(NativeImageGeneratorRunner.java:580)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGeneratorRunner.main(NativeImageGeneratorRunner.java:128)
java.lang.NullPointerException: Cannot invoke "java.lang.Class.getTypeName()" because "aClass" is null
	at org.graalvm.sdk/org.graalvm.nativeimage.hosted.RuntimeClassInitialization.getUnqualifiedName(RuntimeClassInitialization.java:176)
	at org.graalvm.sdk/org.graalvm.nativeimage.hosted.RuntimeClassInitialization.initializeAtRunTime(RuntimeClassInitialization.java:99)
	at io.quarkus.runner.Feature.beforeAnalysis(Unknown Source)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGenerator.lambda$runPointsToAnalysis$9(NativeImageGenerator.java:736)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.FeatureHandler.forEachFeature(FeatureHandler.java:85)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGenerator.runPointsToAnalysis(NativeImageGenerator.java:736)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:578)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGenerator.run(NativeImageGenerator.java:535)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGeneratorRunner.buildImage(NativeImageGeneratorRunner.java:403)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGeneratorRunner.build(NativeImageGeneratorRunner.java:580)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGeneratorRunner.main(NativeImageGeneratorRunner.java:128)
[2/7] Performing analysis...  []                                                                        (15.9s @ 0.95GB)
   7,818 (89.47%) of  8,738 classes reachable
   9,570 (57.86%) of 16,541 fields reachable
  30,143 (79.41%) of 37,959 methods reachable
     173 classes,     0 fields, and     0 methods registered for reflection
Fatal error: com.oracle.graal.pointsto.util.AnalysisError$ParsingError: Error encountered while parsing io.quarkus.runtime.graal.Inet4AnyCidrAccessor.initializeOnce()
Parsing context:
   at io.quarkus.runtime.graal.Inet4AnyCidrAccessor.initializeOnce(CidrAddressSubstitutions.java:55)
   at io.quarkus.runtime.graal.Inet4AnyCidrAccessor.get(CidrAddressSubstitutions.java:49)
   at org.wildfly.common.net.CidrAddress.create(CidrAddress.java:122)
   at org.wildfly.common.net.Inet.parseCidrAddress(Inet.java:686)
   at io.quarkus.runtime.configuration.CidrAddressConverter.convert(CidrAddressConverter.java:27)
   at io.quarkus.runtime.configuration.CidrAddressConverter.convert(CidrAddressConverter.java:16)
   at io.smallrye.config.SmallRyeConfig.convertValue(SmallRyeConfig.java:282)
   at io.smallrye.config.SmallRyeConfig.getValue(SmallRyeConfig.java:242)
   at io.smallrye.config.SmallRyeConfig.getOptionalValue(SmallRyeConfig.java:340)
   at io.smallrye.config.ConfigMappingProvider.mapConfigurationInternal(ConfigMappingProvider.java:981)
   at io.smallrye.config.ConfigMappingProvider.lambda$mapConfiguration$3(ConfigMappingProvider.java:941)
	at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.util.AnalysisError.parsingError(AnalysisError.java:153)
	at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.flow.MethodTypeFlow.createFlowsGraph(MethodTypeFlow.java:104)
	at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.flow.MethodTypeFlow.ensureFlowsGraphCreated(MethodTypeFlow.java:83)
	at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.flow.MethodTypeFlow.getOrCreateMethodFlowsGraph(MethodTypeFlow.java:65)
	at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.typestate.DefaultStaticInvokeTypeFlow.update(DefaultStaticInvokeTypeFlow.java:64)
	at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.PointsToAnalysis$1.run(PointsToAnalysis.java:488)
	at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.util.CompletionExecutor.executeCommand(CompletionExecutor.java:193)
	at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.util.CompletionExecutor.lambda$executeService$0(CompletionExecutor.java:177)
	at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1395)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
Caused by: org.graalvm.compiler.java.BytecodeParser$BytecodeParserError: com.oracle.graal.pointsto.constraints.UnsupportedFeatureException: No instances of java.net.Inet4Address are allowed in the image heap as this class should be initialized at image runtime. To see how this object got instantiated use --trace-object-instantiation=java.net.Inet4Address.
	at parsing io.quarkus.runtime.graal.Inet4AnyAccessor.get(InetSubstitutions.java:43)
	at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.throwParserError(BytecodeParser.java:2518)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.phases.SharedGraphBuilderPhase$SharedBytecodeParser.throwParserError(SharedGraphBuilderPhase.java:110)
	at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.iterateBytecodesForBlock(BytecodeParser.java:3393)
	at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.handleBytecodeBlock(BytecodeParser.java:3345)
	at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.processBlock(BytecodeParser.java:3190)
	at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.build(BytecodeParser.java:1138)
	at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.buildRootMethod(BytecodeParser.java:1030)
	at jdk.internal.vm.compiler/org.graalvm.compiler.java.GraphBuilderPhase$Instance.run(GraphBuilderPhase.java:97)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.phases.SharedGraphBuilderPhase.run(SharedGraphBuilderPhase.java:84)
	at jdk.internal.vm.compiler/org.graalvm.compiler.phases.Phase.run(Phase.java:49)
	at jdk.internal.vm.compiler/org.graalvm.compiler.phases.BasePhase.apply(BasePhase.java:446)
	at jdk.internal.vm.compiler/org.graalvm.compiler.phases.Phase.apply(Phase.java:42)
	at jdk.internal.vm.compiler/org.graalvm.compiler.phases.Phase.apply(Phase.java:38)
	at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.flow.AnalysisParsedGraph.parseBytecode(AnalysisParsedGraph.java:135)
	at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.meta.AnalysisMethod.ensureGraphParsed(AnalysisMethod.java:685)
	at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.phases.InlineBeforeAnalysisGraphDecoder.lookupEncodedGraph(InlineBeforeAnalysis.java:180)
	at jdk.internal.vm.compiler/org.graalvm.compiler.replacements.PEGraphDecoder.doInline(PEGraphDecoder.java:1162)
	at jdk.internal.vm.compiler/org.graalvm.compiler.replacements.PEGraphDecoder.tryInline(PEGraphDecoder.java:1145)
	at jdk.internal.vm.compiler/org.graalvm.compiler.replacements.PEGraphDecoder.trySimplifyInvoke(PEGraphDecoder.java:1003)
	at jdk.internal.vm.compiler/org.graalvm.compiler.replacements.PEGraphDecoder.handleInvoke(PEGraphDecoder.java:957)
	at jdk.internal.vm.compiler/org.graalvm.compiler.nodes.GraphDecoder.processNextNode(GraphDecoder.java:817)
	at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.phases.InlineBeforeAnalysisGraphDecoder.processNextNode(InlineBeforeAnalysis.java:240)
	at jdk.internal.vm.compiler/org.graalvm.compiler.nodes.GraphDecoder.decode(GraphDecoder.java:548)
	at jdk.internal.vm.compiler/org.graalvm.compiler.replacements.PEGraphDecoder.decode(PEGraphDecoder.java:833)
	at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.phases.InlineBeforeAnalysis.decodeGraph(InlineBeforeAnalysis.java:98)
	at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.flow.MethodTypeFlowBuilder.parse(MethodTypeFlowBuilder.java:179)
	at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.flow.MethodTypeFlowBuilder.apply(MethodTypeFlowBuilder.java:349)
	at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.flow.MethodTypeFlow.createFlowsGraph(MethodTypeFlow.java:93)
	... 12 more
Caused by: com.oracle.graal.pointsto.constraints.UnsupportedFeatureException: No instances of java.net.Inet4Address are allowed in the image heap as this class should be initialized at image runtime. To see how this object got instantiated use --trace-object-instantiation=java.net.Inet4Address.
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.classinitialization.ClassInitializationFeature.checkImageHeapInstance(ClassInitializationFeature.java:132)
	at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.meta.AnalysisUniverse.replaceObject(AnalysisUniverse.java:595)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.ameta.AnalysisConstantReflectionProvider.replaceObject(AnalysisConstantReflectionProvider.java:177)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.ameta.AnalysisConstantReflectionProvider.interceptValue(AnalysisConstantReflectionProvider.java:148)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.ameta.AnalysisConstantReflectionProvider.readValue(AnalysisConstantReflectionProvider.java:100)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.ameta.AnalysisConstantReflectionProvider.readFieldValue(AnalysisConstantReflectionProvider.java:79)
	at jdk.internal.vm.compiler/org.graalvm.compiler.nodes.util.ConstantFoldUtil$1.readValue(ConstantFoldUtil.java:55)
	at jdk.internal.vm.compiler/org.graalvm.compiler.core.common.spi.JavaConstantFieldProvider.readConstantField(JavaConstantFieldProvider.java:78)
------------------------------------------------------------------------------------------------------------------------
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.ameta.AnalysisConstantFieldProvider.readConstantField(AnalysisConstantFieldProvider.java:72)
	at jdk.internal.vm.compiler/org.graalvm.compiler.nodes.util.ConstantFoldUtil.tryConstantFold(ConstantFoldUtil.java:51)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.phases.ConstantFoldLoadFieldPlugin.tryConstantFold(ConstantFoldLoadFieldPlugin.java:53)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.phases.ConstantFoldLoadFieldPlugin.handleLoadStaticField(ConstantFoldLoadFieldPlugin.java:49)
	at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.genGetStatic(BytecodeParser.java:4801)
	at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.genGetStatic(BytecodeParser.java:4772)
	at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.processBytecode(BytecodeParser.java:5282)
	at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.iterateBytecodesForBlock(BytecodeParser.java:3385)
	... 37 more
                        0.8s (3.4% of total time) in 18 GCs | Peak RSS: 3.42GB | CPU load: 5.93
========================================================================================================================
Failed generating 'quarkus-camel-xslt-1.0.0-SNAPSHOT-runner' after 22.8s.
Error: Image build request failed with exit status 1
...
```

### Reproducer
* Checkout the project
```bash
git clone git@github.com:turing85/quarkus-camel-xslt.git
cd quarkus-camel-xslt
git fetch
git switch quarkus-2.16.x
```

* Build the project, execute all tests
```bash
./mvn clean package
```

* Notice that execution finishes successfully

* Repeat, but with native compilation activated
```bash
./mvnw --define native clean package
```

* Notice that execution terminates with above error
</details>

**Comment by zhfeng** [comment]
I think the native compiliation issue in `2.16.x` might be introduced by https://github.com/apache/camel-quarkus/commit/bbbee804a215072c217912ffbf922a2438453c52#diff-a130eef52bbd1776c71ac26e7af0628cf828e8be7a005b76b7fa8d3dec556284 and it should check if `camel-quarkus-xslt-saxon` is in the classpath.

**Comment by zhfeng** [comment]
@jamesnetherton @JiriOndrusek can you recall why we need to register `rg.apache.hc.client5.http.impl.auth.NTLMEngineImpl` as `RuntimeInitializedClassBuildItem`. Is it because we need to support `http` schema in camel-xslt component?

**Comment by JiriOndrusek** [comment]
I remember that without , the 'http' tests would fail in the native. Do not recall any more details. It should be easily reproducible.

**Comment by zhfeng** [comment]
Yeah, then can we move this class register to `XmlRouteBuilder` since `camel-xslt` does not depend on any httpclient implementation?

**Comment by zhfeng** [comment]
Sorry, it is `RuntimeinitBuildItem` and can not work with `@RegisterForReflection`. The better way is to remove `org.apache.hc.client5.http.impl.auth.NTLMEngineImpl` registration in `camel-quarkus-xslt` and add `camel-quarkus-support-httpclient` only if we need to use `http` schema in `camel-xslt`.

**Comment by zhfeng** [comment]
Also it needs some document somewhere.

**Comment by turing85** [comment]
@zhfeng @JiriOndrusek I am a little bit confused. You seem to talk about the native compiler error in `2.16.X`, but not about the runtime exception caused by the missing message bundle in `2.13.X`. Is this caused by the same root cause? If so: can we get a downstream patch to LTS `2.13`?

**Comment by zhfeng** [comment]
@turing85 yeah, it should be fixed in https://github.com/apache/camel-quarkus/issues/4710 and @jamesnetherton will take care of backing port it to `2.13.x`.

**Comment by turing85** [comment]
@zhfeng by #4710, you mean #4722? :slightly_smiling_face:

**Comment by zhfeng** [comment]
Hmm, my fault!

- The failure about missing message bundle should be fixed by https://github.com/apache/camel-quarkus/pull/4720 and will backport to `2.13.x`
- registration of `org.apache.hc.client5.impl.auth.NTLMEngineImp` could be fixed by #4722 and IIRC it does not impact `2.13.x`.

I re-open this issue.

**Comment by zhfeng** [comment]
@turing85 I think the issue in 2.16.x should be fixed as a part of https://github.com/apache/camel-quarkus/pull/4753/files#diff-a130eef52bbd1776c71ac26e7af0628cf828e8be7a005b76b7fa8d3dec556284

**Comment by turing85** [comment]
@zhfeng Do we have an ETA for the release of this change? It does not seem to be released with `2.16.6.Final`.

**Comment by zhfeng** [comment]
@turing85 Please check @davsclaus https://github.com/apache/camel-quarkus/pull/4759#issuecomment-1507248944 and I will try to backport https://github.com/apache/camel-quarkus/pull/4753 to `2.16.x`

**Comment by zhfeng** [comment]
The `2.16.x` backport PR: https://github.com/apache/camel-quarkus/pull/4780

**Comment by turing85** [comment]
@zhfeng Is there a possibility to also backport this change to `2.13.x`? A "yes" or "no" is sufficient, I can then do the backport.

**Comment by turing85** [comment]
@zhfeng Do you know whether the fix has been released? I just tried building with quarkus `2.16.7.Final`, and the error keeps appearing.

**Comment by turing85** [comment]
What's more: one project started to show this compilation error after upgrading from quarkus `2.13.2` with camel `3.18.3` to quarkus `2.16.7` with camel `3.20.1`. I am not quite sure what happened, but the project compiled fine before. The xalan-version (`2.7.2`) is identical with both. We do call `XPathAPI`, but other classes from xalan (`org.apache.xalan.xsltc.trax.TransformerFactoryImpl`, `org.apache.xpath.NodeSet` and, `org.apache.xpath.object.XObject` from what I can see). Could it be that the whole dependency is somewhat unstable for native compilation?

**Comment by ppalaga** [comment]
> Do you know whether the fix has been released?

So far the fix is only available in releases 3.0.0-M2 and 3.0.0-RC1.

@essobedo seems to be working on 2.16.1 and he perhaps might want to share the status?

> one project started to show this compilation error

Would you like to paste the error message or stack trace?

**Comment by turing85** [comment]
@ppalaga the compiler error is 1:1 identical with the original message of quarkus 2.16.x. I cannot share the code sadly 😕

**Comment by ppalaga** [comment]
> compiler error is 1:1 identical with the original message of quarkus 2.16.x

Ah, I see thanks for explaining!

**Comment by turing85** [comment]
I think the issue can be closed, right?
