### ISSUE TITLE
2.10.0 not able to boot NoClassDefFoundError: org/apache/camel/builder/ErrorHandlerBuilder

### ISSUE THREAD

**Issue by ennishol** [apache/camel-quarkus#3870]
After upgrading from 2.9.2 to 2.10.0 not able to boot. Unfortunately not able to reproduce in a toy project
```
14:51:10 ERROR [io.qu.ru.bo.StartupActionImpl] (Quarkus Main Thread)  Error running Quarkus: java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at io.quarkus.runner.bootstrap.StartupActionImpl$1.run(StartupActionImpl.java:103)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.ExceptionInInitializerError
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
	at java.base/java.lang.reflect.ReflectAccess.newInstance(ReflectAccess.java:128)
	at java.base/jdk.internal.reflect.ReflectionFactory.newInstance(ReflectionFactory.java:347)
	at java.base/java.lang.Class.newInstance(Class.java:645)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:66)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:41)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:120)
	at io.quarkus.runner.GeneratedMain.main(Unknown Source)
	... 6 more
Caused by: java.lang.RuntimeException: Failed to start quarkus
	at io.quarkus.runner.ApplicationImpl.<clinit>(Unknown Source)
	... 17 more
Caused by: java.lang.NoClassDefFoundError: org/apache/camel/builder/ErrorHandlerBuilder
	at java.base/java.lang.Class.getDeclaredFields0(Native Method)
	at java.base/java.lang.Class.privateGetDeclaredFields(Class.java:3297)
	at java.base/java.lang.Class.getDeclaredField(Class.java:2608)
	at io.quarkus.arc.impl.Reflections.findFieldInternal(Reflections.java:64)
	at io.quarkus.arc.impl.Reflections$1.apply(Reflections.java:33)
	at io.quarkus.arc.impl.Reflections$1.apply(Reflections.java:30)
	at io.quarkus.arc.impl.ComputingCache$1.get(ComputingCache.java:52)
	at io.quarkus.arc.impl.LazyValue.get(LazyValue.java:26)
	at io.quarkus.arc.impl.ComputingCache.computeIfAbsent(ComputingCache.java:69)
	at io.quarkus.arc.impl.ComputingCache.computeIfAbsent(ComputingCache.java:49)
	at io.quarkus.arc.impl.ComputingCache.getValue(ComputingCache.java:40)
	at io.quarkus.arc.impl.Reflections.findField(Reflections.java:59)
	at com.route.MyRoute_Bean.<init>(Unknown Source)
	at io.quarkus.arc.setup.Default_ComponentsProvider.addBeans2(Unknown Source)
	at io.quarkus.arc.setup.Default_ComponentsProvider.getComponents(Unknown Source)
	at io.quarkus.arc.impl.ArcContainerImpl.<init>(ArcContainerImpl.java:124)
	at io.quarkus.arc.Arc.initialize(Arc.java:30)
	at io.quarkus.arc.runtime.ArcRecorder.initContainer(ArcRecorder.java:42)
	at io.quarkus.deployment.steps.ArcProcessor$generateResources1325531031.deploy_0(Unknown Source)
	at io.quarkus.deployment.steps.ArcProcessor$generateResources1325531031.deploy(Unknown Source)
	... 18 more
Caused by: java.lang.ClassNotFoundException: org.apache.camel.builder.ErrorHandlerBuilder
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	at io.quarkus.bootstrap.classloading.QuarkusClassLoader.loadClass(QuarkusClassLoader.java:490)
	at io.quarkus.bootstrap.classloading.QuarkusClassLoader.loadClass(QuarkusClassLoader.java:440)
	... 38 more

```
