### PR TITLE
Remove Nitrite component

### LINKED ISSUE #8246: [quarkus-main] Nitrite integration test native build fails
### Bug description

Native compilation fails with `648 fatal errors detected`.

The logs are full of `NoClassDefFoundError` exceptions for types that are unrelated to Nitrite. I'm not sure why. It could be related to the compiler finding paths to types via the component / endpoint DSLs or the Camel catalog.

Another case possibly caused by https://github.com/quarkusio/quarkus/pull/52313.

Since camel-nitrite is deprecated, there's not much value in investigating too deeply IMO.

I will disable the Nitrite native test profile.

### PR DESCRIPTION
**Pull request by apupier**
it was deprecated in Camel 4.10 and removed in 4.19

fixes #8246

### CODE REVIEW

**Comment by aldettinger** [comment]
Shouldn't camel-quarkus deprecate only and wait for camel to fully remove first ?

**Comment by apupier** [comment]
> Shouldn't camel-quarkus deprecate only and wait for camel to fully remove first ?

it is already deprecated on camel-quarkus side and already removed on Camel side.
Note that the PR is targeting camel-main branch

**Comment by jamesnetherton** [comment]
The failures are already known issues on `camel-main`. So I'll merge to avoid having to do multiple rebases etc when the branch is updated again.
