### PR TITLE
Disable Nitrite native integration tests #8246

### LINKED ISSUE #8246: [quarkus-main] Nitrite integration test native build fails
### Bug description

Native compilation fails with `648 fatal errors detected`.

The logs are full of `NoClassDefFoundError` exceptions for types that are unrelated to Nitrite. I'm not sure why. It could be related to the compiler finding paths to types via the component / endpoint DSLs or the Camel catalog.

Another case possibly caused by https://github.com/quarkusio/quarkus/pull/52313.

Since camel-nitrite is deprecated, there's not much value in investigating too deeply IMO.

I will disable the Nitrite native test profile.

### PR DESCRIPTION
**Pull request by sanjana2505006**
This PR disables the native integration tests for the `camel-quarkus-nitrite` extension.

As reported in #8246, the native build for Nitrite is currently failing with multiple `NoClassDefFoundError`s. Since the `camel-nitrite` component is deprecated and investigating deep native compilation issues provides low value for a deprecated extension, this PR disables the native test execution to unblock the build.

Fixes #8246

### CODE REVIEW

**Comment by sanjana2505006** [comment]
@jamesnetherton Whenever you get a chance, please review and let me know if any changes are needed.

**Comment by jamesnetherton** [comment]
This is already done on a separate branch that will get merged to `main` later this week. Sorry, I should have linked to the commit in the issue.

https://github.com/apache/camel-quarkus/commit/47da4ecd3b77fc87a6e96d7a9db80ac949bbea3c
